# profile 관리
spring:
  profiles:
    default: test
    active: test
# 공통 jpa 설정
jpa:
  generate-ddl: true
  properties:
    hibernate:
      format_sql: true
      show_sql: true
      hbm2ddl:
        auto: validate
  database: oracle
  database-platform: org.hibernate.dialect.OracleDialect